### PR TITLE
Splash Header Update

### PR DESCRIPTION
**Pull request by aditinyn**
Added an image to the background of the header (making it a hero image) with the text written over it, removed the two-column orientation and updated the text color and position accordingly.

### CODE REVIEW

**Review by richardqiu — CHANGES_REQUESTED** [review]
Looks excellent on desktop and larger mobile screens. I have some concerns with the responsiveness on particularly small mobile screens. Can we add some minimum left-padding on particularly small screen sizes? 

image

**Comment by aditinyn** [comment]
Yeah I know. That was a worry of mine as well. I was thinking of getting this pushed first and then if it was okay work on the responsiveness. Will definitely add some left padding for smaller screens and fix the position+right padding too

**Comment by richardqiu** [comment]
I think it'd be a pretty straightforward fix that we should do now rather than pushing off to later. Should be like a couple of lines of CSS at worst.

**Comment by aditinyn** [comment]
Yeah yeah no for sure. Sorry I meant like getting this reviewed before working on the responsiveness to see if any other changes needed to be made. I'm not sure if I'm making any sense right now but I'll do this today.

**Comment by aditinyn** [comment]
Made it responsive for smaller mobile screens and screens with larger heights.

**Review by richardqiu — APPROVED** [review]

**Review by wertyyyy12 — APPROVED** [review]
looks good!

**Pull request merged**
